{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----------------------------------------------------------\n",
      "Financial Analysis\n",
      "----------------------------------------------------------\n",
      "Total Months: 86\n",
      "Total Profits: $38382578\n",
      "Average Change: $7803\n",
      "Greatest Increase in Profits: Feb-2012 ($1926159)\n",
      "Greatest Decrease in Profits: Sep-2013 ($-2196167)\n",
      "----------------------------------------------------------\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import csv\n",
    "\n",
    "\n",
    "PyBankcsv = os.path.join(\"../Resources\",\"budget_data.csv\")\n",
    "\n",
    " \n",
    "profit = []\n",
    "\n",
    "monthly_changes = []\n",
    "\n",
    "date = []\n",
    "\n",
    "#Initialize the variables as required.\n",
    "\n",
    "count = 0\n",
    "total_profit = 0\n",
    "total_change_profits = 0\n",
    "initial_profit = 0\n",
    "\n",
    "#Open the CSV using the set path PyBankcsv\n",
    "\n",
    "with open(PyBankcsv, newline=\"\") as csvfile:\n",
    "\n",
    "    csvreader = csv.reader(csvfile, delimiter=\",\")\n",
    "\n",
    "    csv_header = next(csvreader)\n",
    "\n",
    "\n",
    "    # Conducting the ask\n",
    "\n",
    "    for row in csvreader:    \n",
    "\n",
    "      # Use count to count the number months in this dataset\n",
    "\n",
    "      count = count + 1 \n",
    "\n",
    "      #Will need it when collecting the greatest increase and decrease in profits\n",
    "\n",
    "      date.append(row[0])\n",
    "\n",
    "      #Append the profit information & calculate the total profit\n",
    "\n",
    "      profit.append(row[1])\n",
    "\n",
    "      total_profit = total_profit + int(row[1])\n",
    "\n",
    "\n",
    "      #Calculate the average change in profits from month to month. Then calulate the average change in profits\n",
    "\n",
    "      final_profit = int(row[1])\n",
    "\n",
    "      monthly_change_profits = final_profit - initial_profit\n",
    "\n",
    "\n",
    "      #Store these monthly changes in a list\n",
    "\n",
    "      monthly_changes.append(monthly_change_profits)\n",
    "\n",
    "\n",
    "      total_change_profits = total_change_profits + monthly_change_profits\n",
    "\n",
    "      initial_profit = final_profit\n",
    "\n",
    "      #Calculate the average change in profits\n",
    "\n",
    "      average_change_profits = (total_change_profits/count)\n",
    "\n",
    "      \n",
    "      #Find the max and min change in profits and the corresponding dates these changes were obeserved\n",
    "\n",
    "      greatest_increase_profits = max(monthly_changes)\n",
    "\n",
    "      greatest_decrease_profits = min(monthly_changes)\n",
    "\n",
    "\n",
    "\n",
    "      increase_date = date[monthly_changes.index(greatest_increase_profits)]\n",
    "\n",
    "      decrease_date = date[monthly_changes.index(greatest_decrease_profits)]\n",
    "\n",
    "      \n",
    "\n",
    "    print(\"----------------------------------------------------------\")\n",
    "\n",
    "    print(\"Financial Analysis\")\n",
    "\n",
    "    print(\"----------------------------------------------------------\")\n",
    "\n",
    "    print(\"Total Months: \" + str(count))\n",
    "\n",
    "    print(\"Total Profits: \" + \"$\" + str(total_profit))\n",
    "\n",
    "    print(\"Average Change: \" + \"$\" + str(int(average_change_profits)))\n",
    "\n",
    "    print(\"Greatest Increase in Profits: \" + str(increase_date) + \" ($\" + str(greatest_increase_profits) + \")\")\n",
    "\n",
    "    print(\"Greatest Decrease in Profits: \" + str(decrease_date) + \" ($\" + str(greatest_decrease_profits)+ \")\")\n",
    "\n",
    "    print(\"----------------------------------------------------------\")\n",
    "\n",
    "\n",
    "\n",
    "with open('financial_analysis.txt', 'w') as text:\n",
    "\n",
    "    (\"----------------------------------------------------------\\n\")\n",
    "\n",
    "    (\"  Financial Analysis\"+ \"\\n\")\n",
    "\n",
    "    (\"----------------------------------------------------------\\n\\n\")\n",
    "\n",
    "    (\"    Total Months: \" + str(count) + \"\\n\")\n",
    "\n",
    "    (\"    Total Profits: \" + \"$\" + str(total_profit) +\"\\n\")\n",
    "\n",
    "    (\"    Average Change: \" + '$' + str(int(average_change_profits)) + \"\\n\")\n",
    "\n",
    "    (\"    Greatest Increase in Profits: \" + str(increase_date) + \" ($\" + str(greatest_increase_profits) + \")\\n\")\n",
    "\n",
    "    (\"    Greatest Decrease in Profits: \" + str(decrease_date) + \" ($\" + str(greatest_decrease_profits) + \")\\n\")\n",
    "\n",
    "    (\"----------------------------------------------------------\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
